### ISSUE TITLE
Auto augment V2

### ISSUE THREAD

**Issue by Hzj199** [ymzis69/gddw_track3#1]
有两个问题请教一下：
 1、有比较过v0, v1, v2, v3, test 各个版本的性能差异吗？
2、在这个比赛里 Auto augment V2 的作用大吗？

谢谢分享代码！！！

**Comment by ymzis69** [comment]
有尝试过，v2是最好的，有一定的作用。具体的实验结果我可能需要过几天才有时间找一下发给您。




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "ymzis69/gddw_track3"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年4月16日(星期六) 中午1:32
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;[ymzis69/gddw_track3] Auto augment V2 (Issue #1)





 
有两个问题请教一下：
 1、有比较过v0, v1, v2, v3, test 各个版本的性能差异吗？
 2、在这个比赛里 Auto augment V2 的作用大吗？
 
谢谢分享代码！！！

**Comment by Hzj199** [comment]
> 有尝试过，v2是最好的，有一定的作用。具体的实验结果我可能需要过几天才有时间找一下发给您。
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "ymzis69/gddw_track3" ***@***.***&gt;; 发送时间:&nbsp;2022年4月16日(星期六) 中午1:32 ***@***.***&gt;; ***@***.***&gt;; 主题:&nbsp;[ymzis69/gddw_track3] Auto augment V2 (Issue #1) 有两个问题请教一下： 1、有比较过v0, v1, v2, v3, test 各个版本的性能差异吗？ 2、在这个比赛里 Auto augment V2 的作用大吗？ 谢谢分享代码！！！ — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you are subscribed to this thread.Message ID: ***@***.***&gt;

谢谢！！！期待您的实验结果，邮箱 442142110@qq.com

**Comment by ymzis69** [comment]
@Hzj199 您好，这是我赛道三的实验结果，之所以选择v2而不是v0，是因为在其他赛道v2性能要好过v0。
赛道三的结果：
![D}KINK 1)RGY((T@7BF9U(2](https://user-images.githubusercontent.com/67489888/164665276-bae80798-1161-463e-8411-ffbaed651da7.png)
赛道一的结果：
![QQ截图20220422164902](https://user-images.githubusercontent.com/67489888/164666619-6117aaeb-8321-4f39-b8e5-fe2bc6d65150.jpg)

赛道二的结果：
![QQ截图20220422164959](https://user-images.githubusercontent.com/67489888/164666743-ceb0852f-b5cf-4970-a0ab-ff6d4ec860b9.jpg)

**Comment by Hzj199** [comment]
感谢！！！方便加个好友交流一下吗？

**Comment by Hzj199** [comment]
感谢！！！方便加个好友交流一下吗？

**Comment by ymzis69** [comment]
2253043448，您好，您可以加一下，等等我会关闭这个issue。
